ALTER TABLE MESSAGES
    ADD CHECK (EXTRACT(YEAR FROM TIME_SENT) > 2014);



ALTER TABLE CONTACTS
    ADD CHECK (FNAME IS NOT NULL AND LNAME is NOT NULL AND COUNTRY = 'US' );

CREATE OR REPLACE TRIGGER ChangeSpam
    AFTER UPDATE OR INSERT ON RECIPIENTS
    FOR EACH ROW
    BEGIN
        IF :new.TIME_READ IS NOT NULL THEN
            UPDATE MESSAGES
                SET MESSAGES.SPAM = 0
                WHERE MESSAGES.MSGID = :new.MSGID;
        END IF;
    END;
/

CREATE OR REPLACE TRIGGER Length
    BEFORE INSERT ON MESSAGES
    FOR EACH ROW
    BEGIN
        IF (length(:new.MSG_TEXT) - length(replace(:new.MSG_TEXT, ' ', '')) + 1) > 19 THEN
           :NEW.LENGTH := 1;
        END IF;
    END;
/


CREATE OR REPLACE TRIGGER CreateConversation
    BEFORE INSERT ON MESSAGES
    FOR EACH ROW
    DECLARE num NUMBER;

    BEGIN
        SELECT count(MESSAGES.CONVID) INTO num FROM MESSAGES WHERE MESSAGES.CONVID = :new.CONVID;
        IF num = 0  THEN
            INSERT INTO CONVERSATION VALUES (:NEW.CONVID, :new.SENDER_ID);
        END IF;
    END;
/
